# Generated by Django 5.2.5 on 2025-08-15 11:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_vehicle_price_per_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
